package fit.maurever.layout;

import fit.maurever.implementation.database.Database;
import static fit.maurever.layout.MainFrame.statusbar;

/**
 * Data panel.
 * @author Veronika Maurerova <veronika at maurerova.cz>
 */
public class DataPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataPanel
     */
    public DataPanel() {
        initComponents();
        setDatabaseInformatioLabelText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupPanel = new javax.swing.JPanel();
        groupByLabel = new javax.swing.JLabel();
        hourButton = new javax.swing.JButton();
        dayButton = new javax.swing.JButton();
        monthButton = new javax.swing.JButton();
        yearButton = new javax.swing.JButton();
        deletePanel = new javax.swing.JPanel();
        deleteLabel = new javax.swing.JLabel();
        tableNameLabel = new javax.swing.JLabel();
        deleteField = new javax.swing.JTextField();
        deleteButton = new javax.swing.JButton();
        databaseInformationPanel = new javax.swing.JPanel();
        databaseInformationLabel = new javax.swing.JLabel();
        databaseInformationMainLabel = new javax.swing.JLabel();
        generateFileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        queryTextArea = new javax.swing.JTextArea();
        axisYLabel = new javax.swing.JLabel();
        axisXLabel = new javax.swing.JLabel();
        axisXField = new javax.swing.JTextField();
        axisYField = new javax.swing.JTextField();
        queryLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        groupPanel.setBackground(java.awt.Color.white);

        groupByLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        groupByLabel.setText("Insert GOUP BY template:");

        hourButton.setText("GROUP BY hour");
        hourButton.setToolTipText("");
        hourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourButtonActionPerformed(evt);
            }
        });

        dayButton.setText("GROUP BY day");
        dayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayButtonActionPerformed(evt);
            }
        });

        monthButton.setText("GROUP BY month");
        monthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthButtonActionPerformed(evt);
            }
        });

        yearButton.setText("GROUP BY year");
        yearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groupPanelLayout = new javax.swing.GroupLayout(groupPanel);
        groupPanel.setLayout(groupPanelLayout);
        groupPanelLayout.setHorizontalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupByLabel)
                    .addGroup(groupPanelLayout.createSequentialGroup()
                        .addComponent(hourButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        groupPanelLayout.setVerticalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(groupByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourButton)
                    .addComponent(dayButton)
                    .addComponent(monthButton)
                    .addComponent(yearButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deletePanel.setBackground(java.awt.Color.white);

        deleteLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        deleteLabel.setText("DELETE table:");

        tableNameLabel.setText("Table name:");

        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteLabel)
                    .addGroup(deletePanelLayout.createSequentialGroup()
                        .addComponent(tableNameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(deleteField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(deleteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableNameLabel)
                    .addComponent(deleteButton))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        databaseInformationLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        databaseInformationLabel.setText("Actual database information: ");

        databaseInformationMainLabel.setText("Text");

        javax.swing.GroupLayout databaseInformationPanelLayout = new javax.swing.GroupLayout(databaseInformationPanel);
        databaseInformationPanel.setLayout(databaseInformationPanelLayout);
        databaseInformationPanelLayout.setHorizontalGroup(
            databaseInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databaseInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(databaseInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databaseInformationLabel)
                    .addComponent(databaseInformationMainLabel))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        databaseInformationPanelLayout.setVerticalGroup(
            databaseInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(databaseInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(databaseInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(databaseInformationMainLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        generateFileButton.setText("Generate file");
        generateFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateFileButtonActionPerformed(evt);
            }
        });

        queryTextArea.setColumns(20);
        queryTextArea.setRows(5);
        jScrollPane1.setViewportView(queryTextArea);

        axisYLabel.setText("Name axis Y");

        axisXLabel.setText("Name axis X");

        axisXField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axisXFieldActionPerformed(evt);
            }
        });

        queryLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        queryLabel.setText("Edit GROUP BY query and generate file:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(queryLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(axisXLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(axisXField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(axisYLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(axisYField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(generateFileButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addComponent(deletePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(databaseInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {axisXField, axisYField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(groupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(queryLabel)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(axisXLabel)
                            .addComponent(axisYLabel)
                            .addComponent(axisXField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(axisYField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generateFileButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(databaseInformationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {axisXField, axisYField});

    }// </editor-fold>//GEN-END:initComponents

    private void generateFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateFileButtonActionPerformed
        String query = queryTextArea.getText();
        if (query.contains("SELECT ") && !query.contains(";")) {
            Database.SelectToFile(query, axisXField.getText(), axisYField.getText());
        } else {
            statusbar.setText("Incorrect query! Use correct syntax (only SELECT statement, without ';').");
        }

    }//GEN-LAST:event_generateFileButtonActionPerformed

    private void hourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourButtonActionPerformed
        queryTextArea.setText(Database.univerzalGroupByHour);
        statusbar.setText("Template was generated.");
    }//GEN-LAST:event_hourButtonActionPerformed

    private void dayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayButtonActionPerformed
        queryTextArea.setText(Database.univerzalGroupByDay);
        statusbar.setText("Template was generated.");
    }//GEN-LAST:event_dayButtonActionPerformed

    private void monthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthButtonActionPerformed
        queryTextArea.setText(Database.univerzalGroupByMonth);
        statusbar.setText("Template was generated.");
    }//GEN-LAST:event_monthButtonActionPerformed

    private void yearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearButtonActionPerformed
        queryTextArea.setText(Database.univerzalGroupByYear);
        statusbar.setText("Template was generated.");
    }//GEN-LAST:event_yearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Database.deleteTable(deleteField.getText());
        setDatabaseInformatioLabelText();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void axisXFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axisXFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_axisXFieldActionPerformed

    public void setDatabaseInformatioLabelText() {
        this.databaseInformationMainLabel.setText(Database.getTableInfoHtml());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField axisXField;
    private javax.swing.JLabel axisXLabel;
    private javax.swing.JTextField axisYField;
    private javax.swing.JLabel axisYLabel;
    private javax.swing.JLabel databaseInformationLabel;
    private javax.swing.JLabel databaseInformationMainLabel;
    private javax.swing.JPanel databaseInformationPanel;
    private javax.swing.JButton dayButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField deleteField;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton generateFileButton;
    private javax.swing.JLabel groupByLabel;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JButton hourButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton monthButton;
    private javax.swing.JLabel queryLabel;
    private javax.swing.JTextArea queryTextArea;
    private javax.swing.JLabel tableNameLabel;
    private javax.swing.JButton yearButton;
    // End of variables declaration//GEN-END:variables
}
