package fit.maurever.layout;

/**
 * Manual panel.
 * @author Veronika Maurerova <veronika at maurerova.cz>
 */
public class ManualPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManualPanel
     */
    public ManualPanel() {
        initComponents();
        setManualTextLabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        manualTextLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jLabel2.setText("Manual");

        manualTextLabel.setText("Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manualTextLabel)
                    .addComponent(jLabel2))
                .addContainerGap(1031, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualTextLabel)
                .addContainerGap(446, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel manualTextLabel;
    // End of variables declaration//GEN-END:variables

    public void setManualTextLabel() {
        String text = "<html>"
                + "<h3>1. Introduction</h3>"
                + "<p> </p>"
                + "<h3>2. Upload data to database</h3>"
                + "<p> </p>"
                + "<h3>3. Generate data for regression</h3>"
                + "<p> </p>"
                + "<h3>4. Select data for regression</h3>"
                + "<p> </p>"
                + "<h3>5. View result of regression</h3>"
                + "<p> </p>"
                + "<h3>6. View manual and about</h3>"
                + "<p> </p>"
                + "<html>";
        this.manualTextLabel.setText(text);

    }

}
